### ISSUE TITLE
Enhancement: thermostat-card HACS Support

### ISSUE THREAD

**Issue by cdrom1028** [ciotlosm/lovelace-thermostat-dark-card#252]
Please Add HACS support for ease of deployment and updates. 
https://custom-components.github.io/hacs/

**Comment by ciotlosm** [comment]
I will make a few updates including hacs and probably support for UI Editor

**Comment by james-fry** [comment]
@ciotlosm it would be great to see this in HACS. Your card is by far and away the most impressive thermostat representation I have seen.

**Comment by carldebilly** [comment]
@ciotlosm Any progress on this?

**Comment by DrJohnT** [comment]
Seems someone has published this thermostat control to HACS here:  https://github.com/fineemb/lovelace-thermostat-card

**Comment by danielbrunt57** [comment]
> Seems someone has published this thermostat control to HACS here: https://github.com/fineemb/lovelace-thermostat-card

Yes, but not THIS version of the thermostat-card with `away` mode.

**Comment by ciotlosm** [comment]
This is now being worked on. Currently custom adding the hacs repo works, but the card is still not usable, as it requires visual editor. 
![Screenshot 2020-11-21 at 13 35 44](https://user-images.githubusercontent.com/7738048/99876306-a41d4000-2bfe-11eb-9a05-7600269d0f72.png)

Also docs require an update to show all details required to get to the right state.

**Comment by ciotlosm** [comment]
Apparently to make it work better I have to move the code to a better template based on the boiler card. I'm working on a different repo for now (https://github.com/ciotlosm/lovelace-thermostat-dark-card) that is a fork of boilerplate. Once I"m happy with the setup I'll merge it in the current setup.

**Comment by ciotlosm** [comment]
I did a rollback on this repo for now and will continue development on https://github.com/ciotlosm/lovelace-thermostat-dark-card until finished.

**Comment by ciotlosm** [comment]
This was merged and also added to the offical repo: https://github.com/hacs/default/pull/711#event-4024848858
