### ISSUE TITLE
Card title not show

### ISSUE THREAD

**Issue by PrzemekSkw** [ciotlosm/lovelace-thermostat-dark-card#313]
Hello, I install Dark Thermostat card today and try many configurations but Title not show.
![image](https://github.com/ciotlosm/lovelace-thermostat-dark-card/assets/25219988/b53aba0d-ee10-4dbd-b9ee-614babaf0b75)

**Comment by PrzemekSkw** [comment]
I'm sorry I see now there should be `name` not `title`.
Regards

**Comment by ciotlosm** [comment]
Configuration will be easier in the new redesign version that will allow proper UI
